# set of features that are not compatible with myconfig-maxset.h
FEATURE(DPD)

FEATURE(COMFIXED)

FEATURE(PARTIAL_PERIODIC)
FEATURE(CONSTRAINTS)
FEATURE(EXTERNAL_FORCES)

FEATURE(LENNARD_JONES)

FEATURE(DIPOLES)
FEATURE(METADYNAMICS)

FEATURE(VIRTUAL_SITES_RELATIVE)
FEATURE(VIRTUAL_SITES_NO_VELOCITY)
FEATURE(VIRTUAL_SITES_THERMOSTAT)
FEATURE(THERMOSTAT_IGNORE_NON_VIRTUAL)
FEATURE(ADDITIONAL_CHECKS)
